apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    annotations:
        nginx.ingress.kubernetes.io/backend-protocol: HTTPS
        nginx.ingress.kubernetes.io/proxy-buffer-size: 8k
        nginx.ingress.kubernetes.io/proxy-buffering: "on"
    name: gw-rest-ingress
    namespace: {{ .Values.namespace }}
spec:
    ingressClassName: nginx
    tls:
    - hosts:
        - gw-{{ .Values.database }}.wso2.com
    rules:
    - host: gw-{{ .Values.database }}.wso2.com
      http:
        paths:
        - backend:
            service:
                name: apim-universal-gw-wso2am-universal-gw-service
                port:
                number: 9443
            path: /api/am/gateway/v2/
            pathType: Prefix