apiVersion: v1
kind: Secret
metadata:
  name: test-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
type: Opaque
data:
  git-username: {{ .Values.git_user_name | b64enc | quote }}
  git-password: {{ .Values.git_user_password | b64enc | quote }}
  git-repo: {{ .Values.git_repo | b64enc | quote }}
  git-branch: {{ .Values.git_branch | b64enc | quote }}